---
version: "3"
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/audacity:/config"
      - "${DATA_DIR}:/storage"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3456:3000
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
