http:
  routers:
    adguard:
      entryPoints:
        - https
      rule: 'Host(`adguard.DOMAIN.com`)'
      service: adguard

    olivetin:
      entryPoints:
        - https
      rule: 'Host(`olivetin.DOMAIN.com`)'
      service: olivetin

    homer:
      entryPoints:
        - https
      rule: 'Host(`homer.DOMAIN.com`)'
      service: homer

  services:
    adguard:
      loadBalancer:
        servers:
          - url: http://192.168.29.12:80/

    olivetin:
      loadBalancer:
        servers:
          - url: http://192.168.29.12:1337/

    homer:
      loadBalancer:
        servers:
          - url: http://192.168.29.10:8080/

  ## MIDDLEWARES ##
  middlewares:

    auth:
      forwardauth:
        address: "http://authelia:9091/api/verify?rd=https://authelia.DOMAIN.com/" #chagne authelia:port to containerName:port
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
  
    # Authelia basic auth guard
    auth-basic:
      forwardauth:
        address: "http://authelia:9091/api/verify?auth=basic"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"

    # Security headers
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305