# https://docs.ibracorp.io/authelia/
# https://techno-tim.github.io/posts/authelia-traefik/
---
server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

theme: dark

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: jwt-secret
default_redirection_url: https://DOMAIN.com

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
  - domain: "authelia.DOMAIN.com" # skip authelia or you'll be stuck in a loop
    policy: bypass
    ## catch-all
  - domain: "*.DOMAIN.com"
    subject:
    - "group:admins"
    policy: one_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  secret: your-secret
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  remember_me_duration: 1M
  domain: DOMAIN.com  # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120m
  ban_time: 360m

storage:
  encryption_key: "randomly-generated-key-about-64-characters-long"
  local:
    path: /dbroot/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /dbroot/notification.txt