---
version: "2.1"
services:
  htpcmanager:
    image: lscr.io/linuxserver/htpcmanager:latest
    container_name: htpcmanager
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/htpcmanager:/config"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8085:8085
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
