---
version: "2.1"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: port-ce
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer_data:
networks:
  default:
      external:
          name: web
