# Can't use wireguard with proxied option enabled since they only support selected few ports to be proxied
---
version: "3.8"
services:
  wg-easy:
    image: weejewel/wg-easy:latest
    container_name: wg-cf
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - WG_HOST=${CF_DOMAIN}
      - PASSWORD=${WG_PASS}
      - WG_PORT=51820
      - WG_DEFAULT_DNS=${LOCAL_DNS}
        #      - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24 # doesn't work with this option enabled
    volumes:
      - ${CFG_DIR}/wgcf:/etc/wireguard
    ports:
      - "51820:51820/udp" #wg traffic port; match with WG_PORT
      - "51821:51821/tcp" #webgui port
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
