---
services:
    nebula-sync:
        image: ghcr.io/lovelaze/nebula-sync:latest
        container_name: nebula-sync
        hostname: "nebula-sync-${HOSTNAME}"
        env_file:
            - "${BAK_CFG_DIR}/nebula-sync/.env"
        restart: unless-stopped
        networks:
            - proxy

networks:
    proxy:
        external: true
