---
version: "2.1"
services:
  apprise-api:
    image: linuxserver/apprise-api:latest
    container_name: apprise-api
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${BAK_CFG_DIR}/apprise:/config"
    ports:
      - 8800:8000
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
