---
version: '3.5'
services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    ports:
      - '3002:3001'
    networks:
      - proxy
    labels:
      traefik.enable: true
    environment:
      DASHDOT_SHOW_HOST: true
      DASHDOT_ENABLE_CPU_TEMPS: true
      DASHDOT_ENABLE_STORAGE_SPLIT_VIEW: true
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: true
      DASHDOT_FS_DEVICE_FILTER: 'zram0'
      DASHDOT_FS_VIRTUAL_MOUNTS: 'mergerfs'
      DASHDOT_ACCEPT_OOKLA_EULA: true
    volumes:
      - /:/mnt/host:ro
      - type: bind
        source: ${DEFAULT_INTERFACE_PATH}
        target: /mnt/eth0
    privileged: true
    restart: unless-stopped

networks:
  proxy:
    external: true
