---
version: '3'
services:
  fbacer:
    image: filebrowser/filebrowser:latest
    container_name: fbacer
    user: ${PUID}:${PGID}
    ports:
      - 420:80
    networks:
      - proxy # rename this to your custom docker network
    volumes:
      - ${DATA_DIR}:/srv
      - ${BAK_CFG_DIR}/filebrowser/fbacer/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --noauth #disables auth, don't use this if not using third party auth like authelia

networks:
  proxy:    # rename this to your custom docker network.
    external: true
