version: "3"
services:
  filebrowser:
    container_name: fbrow
    image: hurlenko/filebrowser
    user: 1000:1000
    ports:
      - 420:8080
    volumes:
      - /home/$USER/.config/filebrowser:/config
      - /mnt/merger:/data
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
