---
version: "2.1"
services:
  code:
    image: linuxserver/openvscode-server:latest
    container_name: code
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - CONNECTION_TOKEN= #optional
      # - CONNECTION_SECRET= #optional
      # - SUDO_PASSWORD=password #optional
      # - SUDO_PASSWORD_HASH= #optional
    volumes:
      - "${CFG_DIR}/codeserver:/config"
      - "/home/$USER/.ssh:/config/.ssh"
    ports:
      - 3030:3000
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:    # rename this to your custom docker network.
    external: true
