---
version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    restart: unless-stopped
    networks:
      - proxy # rename this to your custom docker network
    ports:
      - "88:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:

networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
