---
version: '3.3'
services:
  adguard-home:
    image: adguard/adguardhome:latest
    container_name: adguard
    networks:
      - proxy # rename this to your custom docker network
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/adguard/work:/opt/adguardhome/work"
      - "${CFG_DIR}/adguard/conf:/opt/adguardhome/conf"
    ports:
      - 192.168.29.12:53:53/tcp
      - 192.168.29.12:53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    cap_add:
      - NET_ADMIN

networks:
  proxy:    # rename this to your custom docker network.
    external: true
