global:
  checkNewVersion: true
  sendAnonymousUsage: false
ServersTransport:
  insecureSkipVerify: true
  
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: "stag"
        domains:
          - main: DOMAIN.com
            sans:
              - '*.DOMAIN.com'
      middlewares:
        - securityHeaders@file

providers:
  providersThrottleDuration: 2s
    
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

  docker:
    watch: true
    network: proxy
    exposedByDefault: false
    swarmModeRefreshSeconds: 15s
    endpoint: "tcp://dockersocket:2375"

api:
  dashboard: true

log:
  level: DEBUG
  filePath: /etc/traefik/logs/traefik.log

certificatesResolvers:
  prod:
    acme:
      email: mail@domain.com
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

  stag:
    acme:
      email: mail@domain.com
      certificatesDuration: 1
      storage: /etc/traefik/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"