version: "2.1"
services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/putin/.config/prowlarr:/config
      - /home/putin/GitIt/SyncFiles/configBak/prowlarr:/config/Backups
    ports:
      - 9696:9696
    restart: unless-stopped
