---
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=organizr
    volumes:
      - "${CFG_DIR}/prowlarr:/config"
      - "${BAK_CFG_DIR}/prowlarr:/config/Backups"
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
