---
version: "2.1"
services:
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    networks:
      - proxy # rename this to your custom docker network
    # network_mode: "container:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CFG_DIR}/prowlarr:/config"
      - "${BAK_CFG_DIR}/prowlarr:/config/Backups"
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
