---
services:
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=organizr
    volumes:
      - "${CFG_DIR}/prowlarr:/config"
      - "${BAK_CFG_DIR}/prowlarr:/config/Backups"
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${CF_DOMAIN}`)
      traefik.http.routers.prowlarr.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696

#Gluetun for VPN
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - "${BAK_CFG_DIR}/gluetun/Gluetun.conf:/gluetun/config.conf:ro"
    env_file:
      - "${BAK_CFG_DIR}/gluetun/.env"
    ports:
      - 8999:8888/tcp # HTTP proxy
    networks:
      proxy:

#Flaresolerr fro cloudflare
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

networks:
  proxy:
    external: true
