---
version: '3'
services:
  fbpi:
    image: filebrowser/filebrowser:latest
    container_name: fbpi
    user: ${PUID}:${PGID}
    ports:
      - 420:80
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
    volumes:
      - /mnt/Pi_Storage/:/srv
      - ${BAK_CFG_DIR}/filebrowser/fbpi/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --noauth #disables auth, don't use this if not using third party auth like authelia

networks:
  proxy:    # rename this to your custom docker network.
    external: true
