---
version: "3"
services:
  filebrowser:
    container_name: fbrow
    image: hurlenko/filebrowser:latest
    networks:
      - proxy # rename this to your custom docker network
    ports:
      - 420:8080
    volumes:
      - /mnt/Pi_Storage:/data
      - ${CFG_DIR}/filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
