# Can't use wireguard with proxied option enabled since they only support selected few ports to be proxied
# Backup VPN on Pi-Zero
---
services:
  wgeasy:
    environment:
      - HOSTNAME=${HOSTNAME}
      - WG_HOST=wgeasy.${CF_DOMAIN}
      # - PASSWORD=${WG_CL_PASS} ## running behind authentik so don't need password
      - WG_PORT=${WG_PRI_PORT}
      - WG_DEFAULT_DNS=9.9.9.9, 1.1.1.1
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1
      - UI_ENABLE_SORT_CLIENTS=true
      - ENABLE_PROMETHEUS_METRICS=true
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: "wg-${HOSTNAME}" #
    hostname: "wg-${HOSTNAME}" #
    networks:
      - proxy # rename this to your custom docker network
    volumes:
      - ${BAK_CFG_DIR}/wgeasy:/etc/wireguard
    ports:
      - "51820:51820/udp" #wg traffic port; match with WG_PORT
      - "51821:51821/tcp" #webgui port
    labels:
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
      traefik.http.services.wgeasy.loadbalancer.server.port: 51821
      traefik.http.routers.wgeasy.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  proxy:    # rename this to your custom docker network.
    external: true
