---
version: "2.1"
services:
  scrutiny:
    image: linuxserver/scrutiny:latest
    container_name: scrutiny
    networks:
      - proxy # rename this to your custom docker network
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - ${CFG_DIR}/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8780:8080
    devices:
      - /dev/sda:/dev/sda
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
