version: "3.7"
services:
  qbittorrent:
    container_name: qbit
    image: hotio/qbittorrent:release-4.3.9
    ports:
      - "4000:8080"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /home/putin/.config/qbittorrent:/config
      - /mnt/Media/Torrent:/data
    restart: unless-stopped
