---
services:
    postgresql:
        image: postgres:17
        container_name: "keycloak-postgres"
        env_file:
            - "${BAK_CFG_DIR}/keycloak/.env"
        volumes:
            - "${DB_CFG_DIR}/keycloak_postgresql:/var/lib/postgresql/data"
        networks:
            - proxy
        labels:
            com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install
    keycloak:
        image: quay.io/keycloak/keycloak:26.4
        container_name: "keycloak"
        restart: always
        command: start
        depends_on:
            - postgresql
        env_file:
            - "${BAK_CFG_DIR}/keycloak/.env"
        networks:
            - proxy
        ports:
            - 8690:8080
        labels:
            traefik.enable: true
            # traefik.http.services.keycloak.loadbalancer.server.port: portNumber #
            # traefik.http.routers.keycloak.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy
            com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install

networks:
    proxy:
        external: true
