---
version: "3"
services:
  filebrowser:
    image: hurlenko/filebrowser
    user: 1000:1000
    networks:
      - web
    ports:
      - 420:8080
    volumes:
      - /mnt/Pi_Storage:/data
      - /home/$USER/.config/fb:/config
    environment:
      - FB_BASEURL=/filebrowser
    deploy:
      placement:
        constraints:
          - pinux