---
version: "3"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    hostname: grocy
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/grocy:/config" #
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9283:80
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
