---
version: "3"
services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/gotify:/app/data"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GOTIFY_DEFAULTUSER_PASS=pass
    ports:
      - 8500:80
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
