version: "3"
services:
  rustpad: #change me
    image: ekzhang/rustpad:latest #change me
    container_name: rustpad #change me
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3030:3030
    labels:
      traefik.enable: true
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
