version: "2.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/putin/.config/jackett:/config
      - /mnt/Media/Torrent/torrentfiles:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped