---
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
        #      - BASE_URL=/ombi #optional
    volumes:
      - "${CFG_DIR}/ombi:/config"
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
