version: "3.7"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    group_add:
      - 989 #adding group `render` so that VAAPI can use the almighrty radeon r5
      #remeber to change the group id which is present in /etc/group
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Asia/Kolkata
    volumes:
      - /opt/vc/lib:/opt/vc/lib #optional
      - /home/putin/.config/jellyfin:/config
      - /mnt:/data/mnt_dir
      - /mount/Acer_Storage:/data/acer_storage
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #optional
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped



version: "3"
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: "host"
    restart: "unless-stopped"
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes:
      - /etc/jellyfin:/etc/jellyfin
      - /var/cache/jellyfin:/var/cache/jellyfin
      - /var/lib/jellyfin:/var/lib/jellyfin
      - /var/log/jellyfin:/var/log/jellyfin
      - <path-to-media>:<path-to-media>