---
version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - proxy # rename this to your custom docker network
    group_add:
      - 109 #adding group `render` so that VAAPI can use the almighrty radeon r5
      #remeber to change the group id which is present in /etc/group
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=192.168.29.11 #optional
    volumes:
      - "${CFG_DIR}/jellyfin:/config"
      - "${DATA_DIR}:/data"
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #optional
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
