---
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
        #    group_add:
      #      - ${renderGid}
      #      - "989" #adding group `render` so that VAAPI can use the almighrty radeon r5
      #remeber to change the group id which is present in /etc/group
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=media.lan #optional
    volumes:
      - "${CFG_DIR}/jellyfin:/config"
      - "${DATA_DIR}:/data"
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
        #    devices:
        #      - /dev/dri/renderD128:/dev/dri/renderD128
        #      - /dev/dri/card1:/dev/dri/card1
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
