version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    network_mode: "host"
    group_add:
      - 989 #adding group `render` so that VAAPI can use the almighrty radeon r5
      #remeber to change the group id which is present in /etc/group
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - JELLYFIN_PublishedServerUrl=192.168.29.11 #optional
    volumes:
      - /opt/vc/lib:/opt/vc/lib #optional
      - /home/putin/.config/jellyfin:/config
      - /mnt/merger:/data
    # ports:
    #   - 8096:8096
    #   - 8920:8920 #optional
    #   - 7359:7359/udp #optional
    #   - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 #optional
      - /dev/dri/card0:/dev/dri/card0
      # - /dev/vcsm:/dev/vcsm #optional
      # - /dev/vchiq:/dev/vchiq #optional
      # - /dev/video10:/dev/video10 #optional
      # - /dev/video11:/dev/video11 #optional
      # - /dev/video12:/dev/video12 #optional
    restart: unless-stopped