---
version: "2.1"
services:

  full-text-rss:
    container_name: full-text-rss
    ports:
      - '50000:80'
    networks:
      - proxy
    restart: always
    image: 'heussd/fivefilters-full-text-rss:latest'

  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CFG_DIR}/freshrss:/config"
    ports:
      - 89:80
    restart: unless-stopped
    labels:
      traefik.enable: true

networks:
  proxy:    # rename this to your custom docker network.
    external: true
