version: "2.1"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/$USER/.config/freshrss:/config
    ports:
      - 89:80
    restart: unless-stopped