---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/qbittorrent:/config"
      - "${DATA_DIR}/Torrents:/data/Torrents"
      - "${DATA_DIR}/Del:/Del"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=4000
      - TORRENTING_PORT=6881
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    ports:
      - 4000:4000
      - 6881:6881
      - 6881:6881/udp
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
