---
services:
    crowdsec:
        image: crowdsecurity/crowdsec:latest
        container_name: "crowdsec" #
        hostname: "crowdsec-${HOSTNAME}" #
        env_file:
            - "${BAK_CFG_DIR}/crowdsec/.env"
        restart: unless-stopped
        volumes:
            - "${DB_CFG_DIR}/crowdsec_db:/var/lib/crowdsec/data/"
            - "${CFG_DIR}/crowdsec/:/etc/crowdsec/"
            - "${BAK_CFG_DIR}/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml"
            - "${BAK_CFG_DIR}/traefik/logs/:/var/log/traefik/:ro"
        networks:
            - proxy

networks:
    proxy:
        external: true
