---
services:
    crowdsec:
        environment:
            - COLLECTIONS= crowdsecurity/linux crowdsecurity/traefik
        image: crowdsecurity/crowdsec:latest
        container_name: "crowdsec" #
        hostname: "crowdsec-${HOSTNAME}" #
        # env_file:
        #     - "${BAK_CFG_DIR}/crowdsec/.env"
        restart: unless-stopped
        volumes:
            - "${DB_CFG_DIR}/crowdsec_db:/var/lib/crowdsec/data/"
            - "${CFG_DIR}/crowdsec/:/etc/crowdsec/"
            - "${BAK_CFG_DIR}/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml"
            - "${BAK_CFG_DIR}/traefik/logs/:/var/log/traefik/:ro"
        networks:
            - proxy
        # labels:
        #     traefik.enable: true
            # traefik.http.routers.crowdsec.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy

    bouncer-traefik:
        image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
        container_name: bouncer-traefik
        env_file:
            - "${BAK_CFG_DIR}/crowdsec/.env"
        environment:
            #get api key using `docker exec crowdsec cscli bouncers add bouncer-traefik`
            # CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY} 
            CROWDSEC_AGENT_HOST: crowdsec:8080
        networks:
        - proxy
        depends_on:
        - crowdsec
        restart: unless-stopped

networks:
    proxy:
        external: true
