#### Demo config file for headscale stack
http:
  routers:
    headscale:
      rule: 'Host(`HEADSCALE.EXAMPLE.COM`)'
      service: 'headscale'
      middlewares:
        - 'cors'

    rewrite:
      rule: 'Host(`HEADSCALE.EXAMPLE.COM`) && Path(`/`)'
      service: 'headscale'
      middlewares:
        - 'rewrite'

    headscale-grpc:
      rule: "Host(`HEADSCALE-GRPC.EXAMPLE.COM`)"
      entryPoints:
        - https
      tls: true
      service: headscale-grpc
      middlewares:
        - grpcweb

    headplane:
      rule: 'Host(`HEADSCALE.EXAMPLE.COM`) && PathPrefix(`/admin`)'
      service: 'headplane'
      middlewares:
        - 'middlewares-authentik'
    
    headscale-ui:
      rule: 'Host(`HEADSCALE.EXAMPLE.COM`) && PathPrefix(`/web`)'
      service: 'headscale-ui'
      middlewares:
        - 'middlewares-authentik'

  services:
    headscale:
      loadBalancer:
        servers:
          - url: 'http://headscale:8080'

    headscale-grpc:
      loadBalancer:
        servers:
          - url: "h2c://headscale:50443"
        passHostHeader: true

    headplane:
      loadBalancer:
        servers:
          - url: 'http://headplane:3000'

    headscale-ui:
      loadBalancer:
        servers:
          - url: 'http://headscale-ui:8080'

  middlewares:
    rewrite:
      addPrefix:
        prefix: '/admin'
    cors:
      headers:
        accessControlAllowHeaders: '*'
        accessControlAllowMethods:
          - 'GET'
          - 'POST'
          - 'PUT'
        accessControlAllowOriginList:
          - 'https://HEADSCALE.EXAMPLE.COM'
        accessControlMaxAge: 100
        addVaryHeader: true

    grpcweb:
      grpcWeb:
        allowOrigins:
          - "*"


################# WARNING
# Don't do it this stupid way, it is wg traffic so already encrypted
# Just expose these ports directly through container and open ports for udp 3478 and 41641 on your firewall
### Create entrypoint for these two in static traefik.yml config
## Like this:
# ```yml

# ## derp for headscale start
# # for derp server on headscale
#   stun:
#     address: ":3478/udp"
# # maybe for headscale wg interface but not sure
#   headscale-wg:
#     address: ":41641/udp"
# ## derp for headscale finish

# ```
udp:
  routers:
    stun:
      entryPoints:
        - stun
      service: stun-service

    headscale-wg:
      entryPoints:
        - headscale-wg
      service: headscale-wg-service

  services:
    stun-service:
      loadBalancer:
        servers:
          - address: "headscale:3478"

    headscale-wg-service:
      loadBalancer:
        servers:
          - address: "headscale:41641"
