---
services:
    metube:
        # environment:
        #     - PUID=${PUID}
        #     - PGID=${PGID}
        #     - TZ=${TZ}
        #     - HOSTNAME=${HOSTNAME}
        image: ghcr.io/alexta69/metube:latest
        container_name: "metube-${HOSTNAME}" #
        hostname: "metube-${HOSTNAME}" #
        env_file:
            - "${BAK_CFG_DIR}/metube/.env"
        restart: unless-stopped
        volumes:
            - "$DATA_DIR/Media/Metube:/downloads"
        ports:
            - 8081:8081
        networks:
            - proxy
        labels:
            traefik.enable: true
            traefik.http.routers.metube.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy

networks:
    proxy:
        external: true
