version: '3.3'
services:
  adguard-home:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    volumes:
      - /home/$USER/.config/adguard/work:/opt/adguardhome/work
      - /home/$USER/.config/adguard/conf:/opt/adguardhome/conf
    ports:
      - 192.168.29.12:53:53/tcp
      - 192.168.29.12:53:53/udp
      # - 67:67/udp
      # - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    cap_add:
      - NET_ADMIN