---
services:
#scrutiny database
  influxdb:
    container_name: scrutiny_influxdb
    image: influxdb:2.1-alpine
    ports:
        - 8086:8086
    volumes:
        - ${DB_CFG_DIR}/scrutiny_influxdb2/db:/var/lib/influxdb2
        - ${DB_CFG_DIR}/scrutiny_influxdb2/config:/etc/influxdb2
    env_file:
        - "${BAK_CFG_DIR}/scrutiny/.env"
    restart: unless-stopped
    networks:
        - proxy
        - dbs
#scrutiny web gui
  scrutiny:
    container_name: scrutiny
    hostname: scrutiny
    image: ghcr.io/analogj/scrutiny:master-web
    ports:
        - 8780:8080
    volumes:
        - ${BAK_CFG_DIR}/scrutiny:/opt/scrutiny/config
    env_file:
        - "${BAK_CFG_DIR}/scrutiny/.env"
    depends_on:
        - influxdb
    restart: unless-stopped
    networks:
        - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.scrutiny.middlewares: middlewares-authentik@file

networks:
  proxy:
    external: true
  dbs:
    external: true
