---
services:
  fbarch:
    image: filebrowser/filebrowser:latest
    container_name: fbarch
    user: ${PUID}:${PGID}
    ports:
      - 420:80
    networks:
      - proxy # rename this to your custom docker network
    volumes:
      - /:/srv
      - ${BAK_CFG_DIR}/filebrowser/fbarch/filebrowser.db:/database.db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command: --noauth #disables auth, don't use this if not using third party auth like authelia

networks:
  proxy:    # rename this to your custom docker network.
    external: true
