---
version: "3"
services:
  pyload:
    image: lscr.io/linuxserver/pyload-ng:latest
    container_name: pyload
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CFG_DIR}/pyloadng:/config"
      - "${DATA_DIR}/Pyload:/downloads"
    ports:
      - 8100:8000
      # - 9666:9666 #optional
    restart: unless-stopped
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
