services:
  speed: #change me
    image: openspeedtest/latest:latest #change me
    container_name: openspeedtest #change me
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/openspeedtest/config:/config" #change the left side
      - "${CFG_DIR}/openspeedtest/letsencrypt:/var/log/letsencrypt"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3330:3000 #change the left side
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.speed.middlewares: middlewares-authentik@file

networks:
  proxy:    # rename this to your custom docker network.
    external: true
