---
version: "3.1"
services:
  syncthing:
    image: linuxserver/syncthing:latest
    container_name: sync
    hostname: syncthing #optional
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CFG_DIR}/syncthing:/config
      - /home/$USER:/home_dir
      - /:/root_dir
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
