---
version: "3.0"
services:
  littlelink:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    # image: timothystewart6/littlelink-server:latest
    container_name: littlelink
    environment:
      - META_TITLE=Hudater
      - META_DESCRIPTION=Aspiring developer and sysadmin
      - META_AUTHOR=Hudater
      - META_KEYWORDS=HomeLab, Docker, Scripting, Engineering
      - LANG=en
      - META_INDEX_STATUS=all
      - OG_SITE_NAME=Hudater
      - OG_TITLE=Hudater
      - OG_DESCRIPTION=Hudater's headquarters
      - OG_URL=https://haops.dev
      - OG_IMAGE=https://avatars.githubusercontent.com/u/55456200?v=4
      - OG_IMAGE_WIDTH=400
      - OG_IMAGE_HEIGHT=400
      # - GA_TRACKING_ID=G-XXXXXXXXXX
      - THEME=Dark
      - FAVICON_URL=https://avatars.githubusercontent.com/u/55456200?v=4
      - AVATAR_URL=https://avatars.githubusercontent.com/u/55456200?v=4
      - AVATAR_2X_URL=https://avatars.githubusercontent.com/u/55456200?v=4
      - AVATAR_ALT=Hudater Profile Pic
      - NAME=Hudater
      - BIO=Aspiring developer and sysadmin from India | Student
      # use ENV variable names for order, listed buttons will be boosted to the top
      # - BUTTON_ORDER=YOUTUBE,TWITCH,TWITTER,GITHUB,INSTAGRAM,LINKED_IN,DISCORD,FACEBOOK,TIKTOK,PATREON,GEAR,DOCUMENTATION
      # you can render an unlimited amount of custom buttons by adding 
      # the CUSTOM_BUTTON_* variables and by using a comma as a separator.
      - CUSTOM_BUTTON_TEXT=Documentation
      - CUSTOM_BUTTON_URL=https://docs.haops.dev
      - CUSTOM_BUTTON_COLOR=#000000
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff
      - CUSTOM_BUTTON_ALT_TEXT=Documentation for my homelab
      - CUSTOM_BUTTON_NAME=DOCUMENTATION
      - CUSTOM_BUTTON_ICON=fas file-alt
      - GITHUB=https://github.com/hudater
      # - TWITTER=https://l.technotim.live/twitter
      # - INSTAGRAM=https://l.technotim.live/instagram
      # - LINKED_IN=https://l.technotim.live/linkedin
      # - YOUTUBE=https://l.technotim.live/subscribe
      # - TWITCH=https://l.technotim.live/twitch
      # - DISCORD=https://l.technotim.live/discord
      # - TIKTOK=https://l.technotim.live/tiktok
      # - FACEBOOK=https://l.technotim.live/facebook
      # - PATREON=https://l.technotim.live/patreon
      - FOOTER=Hudater © 2022
    ports:
      - 3080:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.littlelink.rule: Host(`${CF_DOMAIN}`) || Host(`www.${CF_DOMAIN}`) #Bypass domain.com and www.domain.com in authelia
      traefik.http.routers.littlelink.entrypoints: https
      traefik.http.routers.littlelink.tls: true
      traefik.http.routers.littlelink.service: littlelink
      traefik.http.services.littlelink.loadbalancer.server.port: 3000

networks:
  proxy:
    external: true
