---
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    networks:
      - proxy
    volumes:
      - /home/$USER/.config/homer:/www/assets
      - "${BAK_CFG_DIR}/homer/config.yml:/www/assets/config.yml"
      - "${BAK_CFG_DIR}/icons:/www/assets/manicons"
      - "${BAK_CFG_DIR}/wallpapers:/www/assets/wallpapers"
    ports:
      - 888:8080
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
    labels:
      traefik.enable: true
      # traefik.http.services.it-tools.loadbalancer.server.port: portNumber #
      traefik.http.routers.homer.middlewares: middlewares-authentik@file 

networks:
  proxy:    # rename this to your custom docker network.
    external: true
