---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    networks:
      - proxy # rename this to your custom docker network
    labels:
      - com.centurylinklabs.watchtower.monitor-only="true"
      - traefik.enable="true"   # Enable Traefik reverse proxy for the Traefik dashboard.
    volumes:
      - /home/$USER/.config/homer:/www/assets
      - "${BAK_CFG_DIR}/homer/config.yml:/www/assets/config.yml"
      - "${BAK_CFG_DIR}/icons:/www/assets/manicons"
      - "${BAK_CFG_DIR}/wallpapers:/www/assets/wallpapers"
    ports:
      - 8080:8080
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
