---
version: '2.4'
services:
  unmanic-gpu:
    container_name: unmanic-gpu
    image: josh5/unmanic:latest
    ports:
      - 8889:8888
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CFG_DIR}/unmanic-gpu:/config
      - /drives/nvme/Unmanic/cache-gpu:/tmp/unmanic
      - /mnt/merger:/library
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE

networks:
  proxy:    # rename this to your custom docker network.
    external: true
