---
version: "3.4"

services:
  collector:
    image: 'ghcr.io/analogj/scrutiny:master-collector'
    container_name: scrutiny_mdsrv
    cap_add:
      - SYS_RAWIO
    volumes:
      - '/run/udev:/run/udev:ro'
    environment:
      COLLECTOR_API_ENDPOINT: ${SCRU_API_ENDPOINT}
      COLLECTOR_HOST_ID: "Workstation"
    devices:
      - "/dev/sda"
    networks:
      - proxy

networks:
  proxy:
    external: true
