---
version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBPASSWORD=${PIHOLE_PASS}
      - FTLCONF_LOCAL_IPV4=192.168.29.10
    # Volumes store your data between container upgrades
    volumes:
      - '${CFG_DIR}/pihole/etc-pihole:/etc/pihole'
      - '${CFG_DIR}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: 80
      com.centurylinklabs.watchtower.monitor-only: true

networks:
  proxy:
    external: true
