---
version: "3"
services:
  notifiarr:
    image: golift/notifiarr:latest
    container_name: notifiarr
    hostname: notifiarr
    restart: unless-stopped
    privileged: true
    volumes:
      - "${BAK_CFG_DIR}/notifiarr/notifiarr.conf:/config/notifiarr.conf"
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-i
      - "${DATA_DIR}:/mnt/merger"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 5454:5454
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
