version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/putin/.config/sonarr:/config
      - /home/putin/GitIt/SyncFiles/configBak/sonarr:/config/Backups
      - /mnt/merger:/data
        #      - /mnt/merger/Media/Shows:/data/Shows
    ports:
      - 8989:8989
    restart: unless-stopped
