---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
    volumes:
      - "${CFG_DIR}/sonarr:/config"
      - "${BAK_CFG_DIR}/sonarr:/config/Backups"
      - "${DATA_DIR}:/data"
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
