---
version: "2.1"
services:
  sonarr:
    image: linuxserver/sonarr:v4
    container_name: sonarr
    networks:
      proxy:
      glue:
          ipv4_address: 172.20.0.22
    labels:
      traefik.enable: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=organizr
    volumes:
      - ${CFG_DIR}/sonarr:/config
      - ${BAK_CFG_DIR}/sonarr:/config/Backups
      - ${DATA_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped

networks:
  proxy:
    external: true
  glue:
    external: true
