---
services:
    omnitools:
        image: iib0011/omni-tools:latest
        container_name: "omnitools-${HOSTNAME}" #
        hostname: "omnitools-${HOSTNAME}" #
        restart: unless-stopped
        # ports:
        #     - 8099:80
        networks:
            - proxy
        labels:
            traefik.enable: true
            traefik.http.routers.omnitools.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
            # com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install

networks:
    proxy:
        external: true
