---
version: "3"
services:
  ersatztv:
    image: jasongdove/ersatztv:latest
    container_name: ersatztv
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/ersatztv:/root/.local/share/ersatztv"
      - "${DATA_DIR}:/path/to/shared/media:ro"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8409:8409
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
