---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - "${CFG_DIR}/jellyseerr:/app/config"
      - "${BAK_CFG_DIR}/jellyseerr/settings.json:/app/config/settings.json"
    ports:
      - 5055:5055
    networks:
      - proxy
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.jellyseerr.rule: Host(`jellyseerr.${CF_DOMAIN}`)
      traefik.http.routers.jellyseerr.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.jellyseerr.loadbalancer.server.port: 5055

networks:
  proxy:
    external: true
