---
services:
    code:
        image: lscr.io/linuxserver/openvscode-server:latest
        container_name: "openvscode-server-${HOSTNAME}" #
        hostname: "openvscode-server-${HOSTNAME}" #
        env_file:
            - "${BAK_CFG_DIR}/openvscode-server/.env"
        restart: unless-stopped
        volumes:
            - "${CFG_DIR}/openvscode-server:/config" #
        ports:
            - 3030:3000
        networks:
            - proxy
        labels:
            traefik.enable: true
            traefik.http.routers.code.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy

networks:
    proxy:
        external: true

