---
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.${CF_DOMAIN}`)
      traefik.http.routers.radarr.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.radarr.loadbalancer.server.port: 7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TP_COMMUNITY_THEME=true
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=catppuccin-mocha
    volumes:
      - ${CFG_DIR}/radarr:/config
      - ${BAK_CFG_DIR}/radarr:/config/Backups
      - ${DATA_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
