---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=organizr
    volumes:
      - ${CFG_DIR}/radarr:/config
      - ${BAK_CFG_DIR}/radarr:/config/Backups
      - ${DATA_DIR}:/data
        #      - "${DATA_DIR}"/Media/Movies:/data/Movies
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
