version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/$USER/.config/radarr:/config
      - /home/$USER/GitIt/SyncFiles/configBak/radarr:/config/Backups
      - /mnt/merger:/data
        #      - /mnt/merger/Media/Movies:/data/Movies
    ports:
      - 7878:7878
    restart: unless-stopped
