---
version: "3.3"
services:
  home:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - "${BAK_CFG_DIR}/homepage:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3333:3000
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
