---
version: '3.8'
services:
  reiverr:
    image: ghcr.io/aleksilassila/:latest
    container_name: reiverr
    hostname: reiverr
    restart: unless-stopped
    volumes:
      - "${BAK_CFG_DIR}/reiverr:/config"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9494:9494
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
