---
services:
    pihole:
        container_name: pihole
        hostname: pihole
        image: jacklul/pihole:latest
        networks:
            dns_net:
                ipv4_address: 172.23.0.6
            proxy:
                # external: true
        ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "85:80/tcp"
        #- "443:443/tcp"
        env_file:
            - "${BAK_CFG_DIR}/pihole/.env"
        volumes:
            - '${CFG_DIR}/pihole/pihole-config/etc-pihole/:/etc/pihole/'
            - '${BAK_CFG_DIR}/pihole/pihole-config/etc-pihole/pihole.toml:/etc/pihole/pihole.toml'
            - '${CFG_DIR}/pihole/pihole-config/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        restart: unless-stopped
        # labels:
        #     - traefik.enable: "true"
        #     - traefik.http.services.pihole.loadbalancer.server.port: "85"
        #     - traefik.http.routers.pihole.middlewares: "middlewares-authentik@file" #add this to any container you want to use the Authentik web proxy
        #     - com.centurylinklabs.watchtower.monitor-only: "true" #to only monitor update with watchtower not install
        labels:
            traefik.enable: true
            traefik.http.services.serviceName.loadbalancer.server.port: 85
            traefik.http.routers.serviceName.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy
            com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install
        
        # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
        cap_add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - NET_RAW
            - SYS_NICE
            - CHOWN


    unbound:
        container_name: unbound
        image: klutchell/unbound:latest
        networks:
            dns_net:
                ipv4_address: 172.23.0.8
            # - proxy
        healthcheck:
        # Use the drill wrapper binary to reduce the exit codes to 0 or 1 for healthchecks
            test: ['CMD', 'drill-hc', '@127.0.0.1', 'dnssec.works']
            interval: 30s
            timeout: 30s
            retries: 3
            start_period: 30s
        volumes:
            - "${BAK_CFG_DIR}/pihole/unbound/pihole.conf:/etc/unbound/custom.conf.d/pihole.conf"
        # ports:
        # - "5053:53/tcp"
        # - "5053:53/udp"
        restart: unless-stopped
        labels:
            com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install

networks:
    dns_net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.23.0.0/16
    proxy:
        external: true
