version: "3"
services:
  pihole:
    hostname: pihole
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "81:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kolkata'
      PIHOLE_DNS_: 127.0.0.1#5053;1.1.1.3;1.0.0.3
    # Volumes store your data between container upgrades
    volumes:
      - '/home/putin/.config/pihole/etc-pihole/:/etc/pihole/'
      - '/home/putin/.config/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped