---
services:
    pihole:
        container_name: pihole
        hostname: pihole
        image: jacklul/pihole:latest
        networks:
            dns_net:
                ipv4_address: 172.23.0.7
            proxy:
        ports:
        - "53:53/tcp"
        - "53:53/udp"
        - "85:80/tcp"
        #- "443:443/tcp"
        env_file:
            - "${BAK_CFG_DIR}/pihole/.env"
        # environment:
        #     TZ: 'Europe/London'
        #     WEBPASSWORD: 'password'
        #     PIHOLE_DNS_: '172.23.0.8#5053'
        volumes:
            - '/home/ubuntu/docker/pihole/etc-pihole/:/etc/pihole/'
            - '/home/ubuntu/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        restart: unless-stopped
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.pihole.entrypoints=http"
            - "traefik.http.routers.pihole.rule=Host(`pihole.yourdomain.com`)"
            - "traefik.http.middlewares.pihole-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.pihole.middlewares=pihole-https-redirect"
            - "traefik.http.routers.pihole-secure.entrypoints=https"
            - "traefik.http.routers.pihole-secure.rule=Host(`pihole.yourdomain.com`)"
            - "traefik.http.routers.pihole-secure.tls=true"
            - "traefik.http.routers.pihole-secure.service=pihole"
            - "traefik.http.services.pihole.loadbalancer.server.port=80"
            - "traefik.docker.network=proxy"

    unbound:
        container_name: unbound
        image: mvance/unbound:latest
        networks:
            dns_net:
                ipv4_address: 172.23.0.8
        volumes:
        - /home/ubuntu/docker/unbound:/opt/unbound/etc/unbound
        ports:
        - "5053:53/tcp"
        - "5053:53/udp"
        restart: unless-stopped

    # pihole:
    #     # environment:
    #     #     - PUID=${PUID}
    #     #     - PGID=${PGID}
    #     #     - TZ=${TZ}
    #     #     - HOSTNAME=${HOSTNAME}
    #     image: MAINTAINER/IMAGE:latest
    #     container_name: "pihole-${HOSTNAME}" #
    #     hostname: "pihole-${HOSTNAME}" #
    #     env_file:
    #         - "${BAK_CFG_DIR}/pihole/.env"
    #     restart: unless-stopped
    #     volumes:
    #         - "${CFG_DIR}/pihole:/config" #
    #     ports:
    #         -80:80 #
    #     networks:
    #         - proxy
    #     labels:
    #         traefik.enable: true
    #         traefik.http.services.pihole.loadbalancer.server.port: portNumber #
    #         traefik.http.routers.pihole.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy
    #         com.centurylinklabs.watchtower.monitor-only: true #to only monitor update with watchtower not install

networks:
    dns_net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.21.0.0/16
    proxy:
        external: true
