---
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      traefik.enable: true
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
