---
services:
  dozzle:
    container_name: "dozzle-${HOSTNAME}" #
    hostname: "dozzle-${HOSTNAME}" #
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    labels:
      traefik.enable: true
      traefik.http.routers.dozzle.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
