---
version: "3"
services:
    hemmelig:
        image: hemmeligapp/hemmelig:latest
        container_name: hemmelig
        hostname: hemmelig
        restart: unless-stopped
        volumes:
        - "${CFG_DIR}/hemmelig:/config" #
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        ports:
        - '3000:3000'
        networks:
        - proxy
        labels:
            traefik.enable: true

networks:
    proxy:
        external: true
