http:
  middlewares:
    htpAuth:
      basicAuth:
        users:
          - "watzenadmin:$apr1$g9w96yDb$tTlj0qQPEmRa7imRwgfPX0"

    auth:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://login.domain.com/
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote- Email

    auth-basic:
      forwardauth:
        address: http://authelia:9091/api/verify?auth=basic
        trustFrowardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote- Email

    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
          X-Forwarded-Proto: "https"
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "strict-origin-when-cross-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true


  routers:
    traefik:
      rule: Host(`traefik.DOMAIN.com`)
      entrypoints:
        - websecure
      middlewares:
        - htpAuth
      service: api@internal