---
version: "2.1"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: code-sv
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - PASSWORD=q #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=q #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
    volumes:
      - "${CFG_DIR}/code:/config"
    ports:
      - 8443:8443
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
