---
version: "2.1"
services:
  budge:
    image: linuxserver/budge:latest
    container_name: budge
    volumes:
      - "${CFG_DIR}/budge:/config" #change the left side
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8880:80 #change the left side
      - 8843:443
    networks:
      - proxy
    labels:
      traefik.enable: true
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true