---
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.unmanic.rule: Host(`unmanic.${CF_DOMAIN}`)
      traefik.http.routers.unmanic.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.unmanic.loadbalancer.server.port: 8888
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CFG_DIR}/unmanic:/config
      - /var/tmp/unmanic:/tmp/unmanic
      - ${DATA_DIR}:/library
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
        #    devices:
        #        - /dev/dri:/dev/dri

networks:
  proxy:    # rename this to your custom docker network.
    external: true
