---
version: '2.4'
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CFG_DIR}/unmanic:/config
      - /lab/acerroot/mnt/merger/Media/Movies:/library/Movies
      - /lab/acerroot/mnt/merger/Media/Shows:/library/Shows
      - /storage/unmanic/cache:/tmp/unmanic
      # - /storage/unmanic/Library:/library
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE

networks:
  proxy:    # rename this to your custom docker network.
    external: true
