---
version: '2.4'
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    ports:
      - 8888:8888
    networks:
      - proxy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - <PATH_TO_CONFIG>:/config
      - <PATH_TO_LIBRARY>:/library
      - <PATH_TO_ENCODE_CACHE>:/tmp/unmanic
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
