---
services:
  wallos:
    image: bellamy/wallos:latest
    container_name: wallos
    hostname: wallos
    restart: unless-stopped
    volumes:
      - '${DB_CFG_DIR}/wallos/db:/var/www/html/db'
      - '${CFG_DIR}/wallos/logos:/var/www/html/images/uploads/logos'
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8282:80
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.wallos.middlewares: middlewares-authentik@file

networks:
  proxy:
    external: true
