---
services:
  it-tools:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME}
    image: corentinth/it-tools:latest
    container_name: "it-tools-${HOSTNAME}" #
    hostname: "it-tools-${HOSTNAME}" #
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/it-tools:/config" #
    ports:
      - 9910:80 #
    networks:
      - proxy
    labels:
      traefik.enable: true
      # traefik.http.services.it-tools.loadbalancer.server.port: portNumber #
      traefik.http.routers.it-tools.middlewares: middlewares-authentik@file #add this to any container you want to use the Authentik web proxy


networks:
  proxy:
    external: true
