---
services:
    cleanuparr:
        image: ghcr.io/cleanuparr/cleanuparr:latest
        container_name: "cleanuparr" #
        hostname: "cleanuparr-${HOSTNAME}" #
        env_file:
            - "${BAK_CFG_DIR}/cleanuparr/.env"
        restart: unless-stopped
        volumes:
            - "${CFG_DIR}/cleanuparr:/config" #
        ports:
            - "11011:11011"
        networks:
            - proxy
        labels:
            traefik.enable: true

networks:
    proxy:
        external: true
