---
services:
    cleanuparr:
        image: ghcr.io/cleanuparr/cleanuparr:latest
        container_name: "cleanuparr" #
        hostname: "cleanuparr-${HOSTNAME}" #
        env_file:
            - "${BAK_CFG_DIR}/cleanuparr/.env"
        restart: unless-stopped
        volumes:
            - "${CFG_DIR}/cleanuparr:/config" #
        ports:
            - "11011:11011"
        networks:
            - proxy
        labels:
            traefik.enable: true
            traefik.http.routers.cleanuparr.rule: Host(`cleanuparr.${CF_DOMAIN}`)
            traefik.http.routers.cleanuparr.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
            traefik.http.services.cleanuparr.loadbalancer.server.port: 11011

networks:
    proxy:
        external: true
