# There is a built-in micro proxy that will host the webui and REST API all on 
# one port (this is called the "Single HTTP Frontend") and means you just need 
# one open port in the container/firewalls/etc. 
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
actions:   

# - title: Restart Computers
#   icon: restart
#   shell: ssh {{ pcIp }} 'sudo reboot'
#   arguments:
#     - name: pcIp
#       title: PC Names
#       choices:
#         - value: putin@192.168.29.10
#         - value: putin@192.168.29.11
#         - value: putin@192.168.29.12
#         - value: putin@192.168.29.40

- title: Restart Computers
  icon: "&#10226;"
  shell: ssh "{{ computers }}" 'sudo reboot'
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: putin@192.168.29.11

        - title: Main PC
          value: putin@192.168.29.40

        - title: Pi4
          value: putin@192.168.29.10

        - title: Pi Zero
          value: putin@192.168.29.12

- title: Poweroff Computers
  icon: "&#9211;"
  shell: ssh "{{ computers }}" 'sudo poweroff'
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: putin@192.168.29.11

        - title: Main PC
          value: putin@192.168.29.40

        - title: Pi4
          value: putin@192.168.29.10

        - title: Pi Zero
          value: putin@192.168.29.12

- title: Boot Computers
  icon: "&#129406;"
  shell: wakeonlan "{{ computers }}"
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: fc:45:96:e7:cf:08

        - title: Main PC
          value: 18:c0:4d:39:0c:ff

        # - title: Pi4
        #   value: putin@192.168.29.10

        # - title: Pi Zero
        #   value: putin@192.168.29.12

# - title: Restart Pi4
#   shell: ssh putin@192.168.29.10 'sudo reboot'
#   icon: ping
#   timeout: 5

# - title: Restart Acer
#   shell: ssh putin@192.168.29.11 'sudo reboot'
#   icon: "&#128187;"
#   timeout: 5

# - title: Restart PiZero
#   shell: ssh putin@192.168.29.12 'sudo reboot'
#   icon: ping
#   timeout: 5

# - title: Restart MainPC
#   shell: ssh putin@192.168.29.40 'sudo reboot'
#   icon: "&#128421;"
#   timeout: 5

- title: Restart Olivetin
  shell: systemctl restart OliveTin
  icon: "&#129746;"
  timeout: 5