---
services:
  myspeed:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME}
    image: germannewsmaker/myspeed:latest
    container_name: "myspeed-${HOSTNAME}" #
    hostname: "myspeed-${HOSTNAME}" #
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/myspeed:/myspeed/data" #
    ports:
      - 5216:5216
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.myspeed.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy


networks:
  proxy:
    external: true
