---
services:
  cloudflared:
    image: erisamoe/cloudflared:latest
    restart: unless-stopped
    container_name: cloudflared
    command: tunnel run traefikHome
    depends_on:
      - mycontainer
    volumes:
      - "${BAK_CFG_DIR}/cloudflared:/etc/cloudflared"
    networks:
      - proxy

networks:
  proxy:
    external: true
