version: "2.1"
services:
  scrutiny:
    image: linuxserver/scrutiny
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - SCRUTINY_API_ENDPOINT=http://localhost:8080
      - SCRUTINY_WEB=true
      - SCRUTINY_COLLECTOR=true
    volumes:
      - /home/putin/.config/scrutiny:/config
      - /run/udev:/run/udev:ro
    ports:
      - 8780:8080
    devices:
      - /dev/nvme0:/dev/nvme0
    restart: unless-stopped
