---
server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug

theme: dark

# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: "JWT-Secret-gen-1"
default_redirection_url: https://DOMAIN.com

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 8
  period: 30
  skew: 1
  secret_size: 32

duo_api:
  hostname: api-hostname.duosecurity.com # from your duo dashboard
  integration_key: integ-key-from-duo-dash
  secret_key: secret-key-from-duo-dash
  disable: false
  enable_self_enrollment: false

ntp:
  address: "time.cloudflare.com:123"
  version: 4
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false


authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024


access_control:
  default_policy: deny
  rules:
  ## Bypass rules for domains
  - domain:
      - "authelia.DOMAIN.com" #otherwise you will be in loop
      - "subdomain.DOMAIN.com"
    policy: bypass

  ## Bypass api / triggers
  - domain: "*.DOMAIN.com"
    resources:
      - "^/api([/?].*)?$"
      - "^/identity.*$"
      - "^/triggers.*$"
      - "^/meshagents.*$"
      - "^/meshsettings.*$"
      - "^/agent.*$"
      - "^/control.*$"
      - "^/meshrelay.*$"
      - "^/wl.*$"
    policy: bypass

  ## Allow free access from local network
  - domain: "*.DOMAIN.com"
    networks:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    policy: bypass

  ## Catch-all
  - domain: "*.DOMAIN.com"
    subject:
    - "group:admins"
    policy: two_factor

session:
  name: authelia_session
  domain: DOMAIN.com
  same_site: lax
  secret: "second-secret-key-from-site"
  expiration: 1y
  inactivity: 6M
  remember_me_duration: 1y
  redis:
    host: authelia_redis
    port: 6379
    password: redis-password-from-docker-compose
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

# storage:
#   encryption_key: "third-secret-key-from-site"
#   mysql:
#     host: authelia_mariadb
#     port: 3306
#     database: authelia
#     username: authelia
#     password: "mariadb-user-pass-from-docker-compose"

storage:
  encryption_key: "generate-with-given-command-using-authelia-image"
  # docker run --rm authelia/authelia:latest authelia crypto rand --length 64 --charset alphanumeric
  postgres:
    host: authelia_postgres
    port: 5432
    database: authelia
    schema: public
    username: authelia
    password: "postgres-user-pass-from-docker-compose"

notifier:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: password-from-google-account-dashboard
    sender: authelia@DOMAIN.com