---
version: "2.1"
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    networks:
      - proxy # rename this to your custom docker network
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - "${CFG_DIR}/heimdall:/config"
    ports:
      - 82:80
      # - 444:443
    labels:
      traefik.enable: true
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
