---
version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=organizr
    volumes:
      - ${CFG_DIR}/bazarr:/config
      - ${BAK_CFG_DIR}/bazarr:/config/backup
      - ${DATA_DIR}/Media:/data/Media
    ports:
      - 6767:6767
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
