version: "2.1"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/$USER/.config/bazarr:/config
      - /home/$USER/GitIt/SyncFiles/configBak/bazarr:/config/Backups
      - /mnt/merger/Media:/data/Media
        #      - /mnt/merger/Shows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
