---
services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.${CF_DOMAIN}`)
      traefik.http.routers.bazarr.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=organizr
    volumes:
      - ${CFG_DIR}/bazarr:/config
      - ${BAK_CFG_DIR}/bazarr:/config/backup
      - ${DATA_DIR}/Media:/data/Media
    ports:
      - 6767:6767
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
