---
version: '3'
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - "${BAK_CFG_DIR}/authelia/:/config"
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entrypoints: https
    expose:
      - 9091
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    healthcheck:
      disable: true
    depends_on:
      - authelia_redis
      # - authelia_mariadb
      - authelia_postgres

## Database section
  authelia_redis:
    container_name: authelia_redis
    image: redis:latest
    command: >
          --requirepass "${AUTHELIA_REDIS_PASS}"
    expose:
      - 6379
    volumes:
      - "${DB_CFG_DIR}/authelia_redis:/data/"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      REDIS_PASSWORD: "${AUTHELIA_REDIS_PASS}"
      TZ: ${TZ}
    networks:
      - proxy
      - dbs
    restart: unless-stopped

  # authelia_mariadb:
  #   container_name: authelia_mariadb
  #   image: linuxserver/mariadb:latest
  #   expose:
  #     - 3306
  #   volumes:
  #     - "${DB_CFG_DIR}/authelia_mariadb:/config"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${AUTHELIA_MYSQL_ROOT_PASS}"
  #     MYSQL_ROOT_USER: root
  #     MYSQL_DATABASE: authelia
  #     MYSQL_USER: authelia
  #     MYSQL_PASSWORD: "${AUTHELIA_MYSQL_USER_PASS}"
  #   networks:
  #     - proxy
  #     - dbs
  #   restart: unless-stopped

  authelia_postgres:
    container_name: authelia_postgres
    image: postgres:latest
    expose:
      - 5432
    volumes:
      - "${DB_CFG_DIR}/authelia_postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: authelia
      POSTGRES_PASSWORD: "${AUTHELIA_MYSQL_USER_PASS}"
      POSTGRES_DB: authelia
    networks:
      - proxy
      - dbs
    restart: unless-stopped

networks:
  proxy:
    external: true
  dbs:
    external: true
