---
version: '3'
services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - "${BAK_CFG_DIR}/authelia/:/config"
      - "${CFG_DIR}/authelia/:/dbroot"
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entrypoints: https
    expose:
      - 9091
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    healthcheck:
      disable: true

networks:
  proxy:
    external: true
