version: "2"
services:
  guacamole:
    image: maxwaldorf/guacamole
    container_name: guacamole
    volumes:
      - /home/putin/.config/guacamole:/config
    ports:
      - 8888:8080
    restart: unless-stopped