---
services:
  serviceName:
    image: MAINTAINER/IMAGE:latest
    container_name: myContainer #
    hostname: myContainer #
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/containerCfgDir:/config" #
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 80:80 #
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.services.portainer.loadbalancer.server.port: portNumber #

networks:
  proxy:
    external: true
