version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime
    volumes:
      - /home/putin/.config/uptime:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true