version: "2.1"
services:
  libreoffice:
    image: linuxserver/libreoffice
    container_name: libreoffice
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /home/putin/.config/libreoffice:/config
    ports:
      - 3003:3000
    restart: unless-stopped