version: '2.1'
services:
  hammond:
    image: akhilrex/hammond:latest
    container_name: hammond
    volumes:
      - "${CFG_DIR}/hammond/config:/config"
      - "${CFG_DIR}/hammond/assets:/assets"
    ports:
      - 3300:3000
    restart: unless-stopped
    networks:
          - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
