---
version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    networks:
      - proxy # rename this to your custom docker network
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - "${BAK_CFG_DIR}/traefik/:/etc/traefik/"
    labels:
      traefik.http.routers.api.rule: Host(`traefik.${CF_DOMAIN}`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    environment:
      CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
      CF_API_EMAIL: "${CF_API_EMAIL}"
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
