---
version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # ro = read-only access to the docker.sock
      - /home/$USER/GitIt/SyncFiles/configBak/traefik/:/etc/traefik/
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.http.routers.api.rule: Host(`traefik.DOMAIN.com`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    environment:
      CF_API_KEY: Global-API-Key
      CF_DNS_API_TOKEN: Custom-DNS-Api-Token
      CF_API_EMAIL: email@email.com
    restart: unless-stopped


networks:
  proxy:    # rename this to your custom docker network.
    driver: bridge
    external: true
