---
version: "2.1"
services:
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=organizr
    volumes:
      - ${CFG_DIR}/lidarr:/config
      - ${BAK_CFG_DIR}/lidarr:/config/Backups
      - ${DATA_DIR}:/data
    ports:
      - 8686:8686
    restart: unless-stopped

networks:
  proxy:    # rename this to your custom docker network.
    external: true
