---
version: "3"
services:
  posterr:
    image: petersem/posterr:latest
    container_name: posterr
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/posterr/config:/usr/src/app/config"
      - "${CFG_DIR}/posterr/custom:/usr/src/app/public/custom"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 9876:3000
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
