---
# There is a built-in micro proxy that will host the webui and REST API all on 
# one port (this is called the "Single HTTP Frontend") and means you just need 
# one open port in the container/firewalls/etc. 
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Actions (buttons) to show up on the WebUI:
actions:

- title: Restart Computers
  icon: "&#10226;"
  shell: ssh "{{ computers }}" 'sudo reboot'
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: putin@acer.lan

        - title: Main PC
          value: putin@pc.lan

        - title: Pi4
          value: putin@pi.lan

        - title: Pi Zero
          value: putin@pero.lan

- title: Poweroff Computers
  icon: "&#9211;"
  shell: ssh "{{ computers }}" 'sudo poweroff'
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: putin@acer.lan

        - title: Main PC
          value: putin@pc.lan

        - title: Pi4
          value: putin@pi.lan

        - title: Pi Zero
          value: putin@pero.lan

- title: Boot Computers
  icon: "&#129406;"
  shell: wakeonlan "{{ computers }}"
  arguments:
    - name: computers
      choices:
        - title: Acer
          value: fc:45:96:e7:cf:08

        - title: Main PC
          value: 18:c0:4d:39:0c:ff

- title: Monitor Functions
  icon: "&#128437;"
  shell: ssh putin@pc.lan 'xset -display :0 dpms force "{{ function }}"'
  arguments:
    - name: function
      choices:
        - title: Turn Monitor On
          value: "on"

        - title: Turn Monitor Off
          value: "off"

- title: Restart AdGuard
  shell: systemctl restart AdGuardHome.service
  icon: "&#8962;"
  timeout: 5

- title: Restart Olivetin
  shell: systemctl restart OliveTin
  icon: "&#129746;"
  timeout: 5
