---
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    hostname: pinchflat
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/pinchflat:/config"
      - "${DATA_DIR}/Media/Youtube:/downloads"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - '8945:8945'
    networks:
      - proxy
    labels:
      traefik.enable: true

networks:
  proxy:
    external: true
