---
services:
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    container_name: pinchflat
    hostname: pinchflat
    restart: unless-stopped
    volumes:
      - "${CFG_DIR}/pinchflat:/config"
      - "${DATA_DIR}/Media/Youtube:/downloads"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ENABLE_PROMETHEUS=1
    ports:
      - '8945:8945'
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.pinchflat.rule: Host(`pinchflat.${CF_DOMAIN}`)
      traefik.http.routers.pinchflat.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.services.pinchflat.loadbalancer.server.port: 8945

networks:
  proxy:
    external: true
