---
services:
  #UI dashboard
  dashboard:
    image: netbirdio/dashboard:latest
    restart: unless-stopped
    container_name: netbird-dash
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://netbird.${CF_DOMAIN}:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://netbird.${CF_DOMAIN}:443
      # OIDC
      - AUTH_AUDIENCE=${NETBIRD_AUTH_CLIENT_ID_SHELL_ENV}
      - AUTH_CLIENT_ID=${NETBIRD_AUTH_CLIENT_ID_SHELL_ENV}
      - AUTH_CLIENT_SECRET=
      - AUTH_AUTHORITY=https://authentik.${CF_DOMAIN}/application/o/netbird/
      - USE_AUTH0=false
      - AUTH_SUPPORTED_SCOPES=openid profile email offline_access api
      - AUTH_REDIRECT_URI=
      - AUTH_SILENT_REDIRECT_URI=
      - NETBIRD_TOKEN_SOURCE=accessToken
      # SSL
      - NGINX_SSL_PORT=443
      # Letsencrypt
      - LETSENCRYPT_DOMAIN=
      - LETSENCRYPT_EMAIL=
    volumes:
      - netbird-letsencrypt:/etc/letsencrypt/
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-dashboard.rule=Host(`netbird.${CF_DOMAIN}`)
      - traefik.http.services.netbird-dashboard.loadbalancer.server.port=80

  # Signal
  signal:
    image: netbirdio/signal:latest
    restart: unless-stopped
    container_name: netbird-signal
    volumes:
      - netbird-signal:/var/lib/netbird
    # ports:
    #   - 443:80
  #      # port and command for Let's Encrypt validation
  #      - 443:443
  #    command: ["--letsencrypt-domain", "", "--log-file", "console"]
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-signal.rule=Host(`netbird.${CF_DOMAIN}`) && PathPrefix(`/signalexchange.SignalExchange/`)
      - traefik.http.services.netbird-signal.loadbalancer.server.port=80
      - traefik.http.services.netbird-signal.loadbalancer.server.scheme=h2c


  # Relay
  relay:
    image: netbirdio/relay:latest
    restart: unless-stopped
    container_name: netbird-relay
    environment:
    - NB_LOG_LEVEL=info
    - NB_LISTEN_ADDRESS=:33080
    - NB_EXPOSED_ADDRESS=netbird.${CF_DOMAIN}:33080
    # todo: change to a secure secret
    - NB_AUTH_SECRET=${NETBIRD_NB_AUTH_SECRET}
    ports:
      - 33080:33080
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-relay.rule=Host(`netbird.${CF_DOMAIN}`) && PathPrefix(`/relay`)
      - traefik.http.services.netbird-relay.loadbalancer.server.port=33080


  # Management
  management:
    image: netbirdio/management:latest
    restart: unless-stopped
    container_name: netbird-mgmt
    depends_on:
      - dashboard
    volumes:
      - netbird-mgmt:/var/lib/netbird
      - netbird-letsencrypt:/etc/letsencrypt:ro
      - "${BAK_CFG_DIR}/netbird/management.json:/etc/netbird/management.json"
    # ports:
    #   - 443:443 #API port
  #    # command for Let's Encrypt validation without dashboard container
  #    command: ["--letsencrypt-domain", "", "--log-file", "console"]
    command: [
      "--port", "443",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
      "--single-account-mode-domain=netbird.${CF_DOMAIN}",
      "--dns-domain=netbird.selfhosted"
      ]
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"
    environment:
      - NETBIRD_STORE_ENGINE_POSTGRES_DSN=
      - NETBIRD_STORE_ENGINE_MYSQL_DSN=
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbird-api.rule=Host(`netbird.${CF_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.netbird-api.service=netbird-api
      - traefik.http.services.netbird-api.loadbalancer.server.port=443
      - traefik.http.routers.netbird-management.rule=Host(`netbird.${CF_DOMAIN}`) && PathPrefix(`/management.ManagementService/`)
      - traefik.http.routers.netbird-management.service=netbird-management
      - traefik.http.services.netbird-management.loadbalancer.server.port=443
      - traefik.http.services.netbird-management.loadbalancer.server.scheme=h2c

  # Coturn
  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    container_name: netbird-coturn
    #domainname: netbird.${CF_DOMAIN} # only needed when TLS is enabled
    volumes:
      - "${BAK_CFG_DIR}/netbird/turnserver.conf:/etc/turnserver.conf:ro"
    #      - ./privkey.pem:/etc/coturn/private/privkey.pem:ro
    #      - ./cert.pem:/etc/coturn/certs/cert.pem:ro
    network_mode: host
    command:
      - -c /etc/turnserver.conf
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "2"

volumes:
  netbird-mgmt:
  netbird-signal:
  netbird-letsencrypt:

networks:
  proxy:
    external: true
