---
# change network names
version: '3.8'
networks:
  proxy:
    driver: bridge
    external: true
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./tra:/etc/traefik/
    networks:
      - proxy
    labels:
      traefik.http.routers.api.rule: Host(`traefik.DOMAIN.com`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.
    environment:
      TZL: US/Central
      DOCKER_HOSTL: dockersocket
      CF_API_EMAILL: mail@domain.com
      CF_DNS_API_TOKENL: your-token
    restart: unless-stopped
    depends_on:
      - dockersocket

  dockersocket:
    container_name: dockersocket
    image: tecnativa/docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    environment:
      CONTAINERS: 1
      POST: 0
    privileged: true
    restart: unless-stopped